### ISSUE TITLE
Load the current date

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [Your-News-On-Time/YourNewsonTime#11]
# Description

Load the current date on the `Feed` screen header, updating it in real time.

# Tasks

- [x] Load date from device
- [x] Show the date on the header
- [x] Update it when the device date changes
