### ISSUE TITLE
Create Footer component

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [Your-News-On-Time/YourNewsonTime#13]
# Description

Create a Footer component with:

* Left button with three parallel lines icon which loads the menu modal from the left side of the screen.
* Button with a home icon which loads the `Feed` screen or reloads it if the screen is already `Feed`.
* Button that includes the bookmark icon to navigate to the `Saved News` screen.
* Button with a profile icon to navigate to the `Profile` screen.

# Tasks

- [x] Button with 3 parallel lines icon
- [x] Modal that appears from the left side of the screen
- [x] Button with today's calendar icon
- [x] Button with a bookmark icon
- [x] Button with a profile icon
