### ISSUE TITLE
Create Profile screen

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [Your-News-On-Time/YourNewsonTime#16]
# Description

A screen (it should look like a journalist's card) on which a registered user can view their account details:

* The profile picture
* The nickname
* The e-mail address with which it has registered
* The way with which it has registered

The card has to use the gyroscope sensor to give a 3D effect when moving the mobile phone.

There is an option to edit the photo (to take it with the phone camera), nickname and password (only if it was registered with email and password).

# Tasks

- [x] Simulate a card
- [x] Show the profile picture from Google account
- [x] Show the nickname
- [x] Show the e-mail
- [x] Show how it was registered
- [x] #38
- [x] #37

**Comment by JuanCarlosAcostaPeraba** [comment]
Idea for the card view:

![Image](https://github.com/user-attachments/assets/e1b5bf07-43f1-4029-9f2a-9f1dcea05ce5)
