### ISSUE TITLE
Filter by categories

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [Your-News-On-Time/YourNewsonTime#17]
# Description

Create a feature to search by different categories modifying the The New York Times API query.
When a user selects one category, the query must change and load only that category news on the `Feed` screen.

# Tasks

- [x] Abstract the category types to use easily
- [x] List types on the modal ( #13 )
- [x] Update the list when changing the following preferences
- [x] Switch the query API to adapt the search
