### ISSUE TITLE
Add Coil dependency

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [Your-News-On-Time/YourNewsonTime#20]
# Description

Add Coil dependency to get images from the Internet

# Tasks

- [x] Add dependency Coil
- [x] Get images from news
- [x] Get profile image from Google account
