### ISSUE TITLE
Create Sign Up screen

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [Your-News-On-Time/YourNewsonTime#4]
# Description

This screen must have three input fields where the user should write their registration email, the account password, and the password confirmation.
There is a button to submit all the registration data and two separate buttons the left one indicates the sign-in with Google, and the right one is for guest users who don't want to log in on the app.

# Tasks

- [x] Email input field
- [x] Password input field
- [x] Confirm password input field
- [x] Submit button
- [x] Google Sign-in button
- [x] Guest button
