### ISSUE TITLE
Create Start screen

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [Your-News-On-Time/YourNewsonTime#5]
# Description

This screen is the first screen that loads when you open the app for the first time.
It must contain descriptive text that explains what the app is about for the user, a button with the text "Get started" and a modal with all the different options for Signing up.

# Tasks

- [x] Image with icons symbolizing the news categories
- [x] Descriptive text
- [x] "Get started" button
- [x] Modal with buttons for Sign up
